# Generated by Django 2.0 on 2018-01-15 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Besoin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Le quantité')),
                ('price', models.IntegerField(verbose_name='Le Prix')),
                ('marge', models.FloatField(default=1.0, null=True)),
                ('remise', models.FloatField(default=1.0, null=True)),
            ],
        ),
    ]
