# Generated by Django 2.0 on 2018-01-15 08:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('personneabout', models.CharField(max_length=150)),
                ('ville', models.CharField(max_length=25)),
                ('description', models.TextField()),
                ('created', models.DateField(auto_now_add=True)),
                ('marge', models.FloatField(default=1.0, null=True)),
                ('remise', models.FloatField(default=1.0, null=True)),
                ('activities', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='activities.Activitie')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clients.Client')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
