# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-18 22:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainoeuvres', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainoeuvre',
            name=b'montant',
            field=models.IntegerField(verbose_name=b'Cout horaire HT'),
        ),
    ]
