# Generated by Django 2.0 on 2018-01-15 08:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clientcode', models.CharField(max_length=25)),
                ('clientname', models.CharField(max_length=150)),
                ('clientraison', models.CharField(max_length=150)),
                ('clientcontact', models.CharField(max_length=15)),
                ('clientcity', models.CharField(max_length=15)),
                ('clientcountry', models.CharField(max_length=15)),
                ('clientfax', models.CharField(max_length=15)),
                ('clientemail', models.EmailField(max_length=25)),
                ('clientreglement', models.CharField(max_length=50)),
                ('created', models.DateField(auto_now_add=True)),
                ('clientactivite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activities.Activitie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
