# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-18 23:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_auto_20180218_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='clientcountry',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='client',
            name='clientemail',
            field=models.EmailField(max_length=250),
        ),
        migrations.AlterField(
            model_name='client',
            name='clientfax',
            field=models.CharField(max_length=150),
        ),
    ]
