# Generated by Django 2.0 on 2018-01-15 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('outils', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectOutil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valeur', models.IntegerField(editable=False, verbose_name='Valeur')),
                ('quantite', models.IntegerField(verbose_name='Quantité necessaire')),
                ('duree', models.IntegerField(verbose_name='Nombre de jours')),
                ('montant', models.IntegerField(blank=True, null=True, verbose_name='Montant')),
                ('outil', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='outils.Outil')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projects.Project')),
            ],
        ),
    ]
