# Generated by Django 2.0 on 2018-01-15 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Devi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroproforma', models.CharField(max_length=150, verbose_name='Numero de la proforma : ')),
                ('nomproforma', models.CharField(max_length=150, verbose_name='Nom de la proforma     :')),
                ('personneabout', models.CharField(max_length=150, verbose_name="A l'attention de  : ")),
                ('delailivraison', models.CharField(max_length=150, verbose_name='Delai de livraison : ')),
                ('finvalidate', models.CharField(max_length=150, verbose_name='Date de fin de validité : ')),
                ('datedemande', models.CharField(max_length=150, verbose_name='Date de demande : ')),
                ('avance', models.IntegerField(verbose_name='Avance en % : ')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clients.Client')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projects.Project')),
            ],
        ),
    ]
