# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-24 12:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        ('produits', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Devi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroproforma', models.CharField(max_length=150, verbose_name='Numero de la proforma : ')),
                ('delailivraison', models.CharField(max_length=150, verbose_name='Delai de livraison : ')),
                ('finvalidate', models.DateField(verbose_name='Date de fin de validité : ')),
                ('datedemande', models.DateField(max_length=150, verbose_name='Date de demande : ')),
                ('avance', models.IntegerField(verbose_name='Avance en % : ')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projects.Project')),
            ],
        ),
        migrations.CreateModel(
            name='devis_config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compact', models.BooleanField()),
                ('created', models.DateField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='produits.Product')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projects.Project')),
            ],
        ),
    ]
