# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-24 12:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devis_config',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='besoins.Besoin'),
        ),
    ]
