# Generated by Django 2.0 on 2018-01-15 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devis', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devi',
            name='client',
        ),
        migrations.RemoveField(
            model_name='devi',
            name='personneabout',
        ),
        migrations.AlterField(
            model_name='devi',
            name='datedemande',
            field=models.DateField(max_length=150, verbose_name='Date de demande : '),
        ),
        migrations.AlterField(
            model_name='devi',
            name='finvalidate',
            field=models.DateField(verbose_name='Date de fin de validité : '),
        ),
    ]
