# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-24 13:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devis', '0002_auto_20180124_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='devis_config',
            name='parent',
            field=models.CharField(default="None", max_length=100),
        ),
    ]
