# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-24 13:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devis', '0003_devis_config_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devis_config',
            name='parent',
            field=models.CharField(max_length=100),
        ),
    ]
