# Generated by Django 2.0 on 2018-01-15 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('contact', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('ville', models.CharField(max_length=150)),
                ('created', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
