# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-18 22:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fournisseurs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fournisseur',
            name=b'email',
        ),
        migrations.AddField(
            model_name='fournisseur',
            name='cel',
            field=models.CharField(default=None, max_length=20, verbose_name=b'Cel'),
        ),
        migrations.AlterField(
            model_name='fournisseur',
            name=b'contact',
            field=models.CharField(max_length=150, verbose_name=b'Telephone'),
        ),
        migrations.AlterField(
            model_name='fournisseur',
            name=b'name',
            field=models.CharField(max_length=150, verbose_name=b'Raison social'),
        ),
        migrations.AlterField(
            model_name='fournisseur',
            name=b'ville',
            field=models.CharField(max_length=150, verbose_name=b'Ville'),
        ),
    ]
