# Generated by Django 2.0 on 2018-01-15 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transports', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectTransports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coutkm', models.IntegerField(editable=False, null=True, verbose_name='Cout au KM')),
                ('distance', models.IntegerField(verbose_name='Distance KM')),
                ('coefficient', models.IntegerField(verbose_name='Coefficient %')),
                ('montant', models.IntegerField(verbose_name='Montant')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projects.Project')),
                ('transport', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transports.Transport')),
            ],
        ),
    ]
