# Generated by Django 2.0 on 2018-01-15 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fournisseurs', '__first__'),
        ('materiels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=25)),
                ('name', models.CharField(max_length=25)),
                ('quantity', models.IntegerField()),
                ('price', models.IntegerField()),
                ('online', models.BooleanField()),
                ('created', models.DateField(auto_now_add=True)),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fournisseurs.Fournisseur')),
                ('type_materiel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materiels.Materiel')),
            ],
        ),
    ]
