# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-18 22:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fournisseurs', '0002_auto_20180218_2249'),
    ]

    operations = [
        migrations.CreateModel(
            name='FournisseurContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('fonction', models.CharField(max_length=50)),
                ('cel', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50)),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fournisseurs.Fournisseur')),
            ],
        ),
    ]
